### ISSUE TITLE
App Marketplace

### ISSUE THREAD

**Issue by engramar** [codesydney/codesydneywebsite#13]
A place where developers can sell their niche apps

**Comment by engramar** [comment]
Morning @EllaFerreira, This is what I think would add some huge value on our website. =)

**Comment by engramar** [comment]
Hi @EllaFerreira , As a start, you can just copy the same implementation as that of the Volunteers page. Essentially Marketplace is where local delivers showcase their personal projects for potential public use or even monetisation. 
As of this moment, we only have one app to be published on our marketplace. It will sort of like a google play store or apple play store. 
We just list down all apps, developers and links to their websites. No need to be fancy at this stage. Thanks.

**Comment by engramar** [comment]
Here is a more advanced example of a typical marketplace https://appexchange.salesforce.com/category/analytics
For us, we just need the most basic for now. Just show the app and searchable by name or type like our volunteers page. Thanks again.

**Comment by engramar** [comment]
For the initial version, we can keep the app info as minimal as possible
- App Name (link to app website)
- App Short Description
- Category
- Developer (link to developer website)

and search can be done across all four above (similar to our volunteers page)
Thanks again.

**Comment by EllaFerreira** [comment]
Hello @engramar which app you want me to add to the Marketplace page?
