### ISSUE TITLE
Lead to right page position after clicking page link

### ISSUE THREAD

**Issue by Luukeeeee** [codesydney/codesydneywebsite#26]
After clicking links on navbar, scroll the page to skip the header and the slider section for better UX.

**Comment by QjStout** [comment]
Should we just remove the header all together from pages that's aren't Home? Or alternatively, those pages could have a small version that goes inside the navbar

**Comment by Luukeeeee** [comment]
Or we can leave the navbar and just remove the slider section for and add a codesydney icon on the navbar for pages  not home?

**Comment by QjStout** [comment]
Yeah, that's what I was trying to get at with the 2nd option. You phrased it more clearly than me though.
Make the logo clickable and route back to home

**Comment by Luukeeeee** [comment]
@QjStout Agree, just see any new coming volunteer wants to contribute.

**Comment by infodsagar** [comment]
Happy to work on this one. Can anyone explain the issue again?

**Comment by davidtaing** [comment]
All yours @NimaSakha!
