### ISSUE TITLE
bug: Contributors Creates Array on Each Render

### ISSUE THREAD

**Issue by davidtaing** [codesydney/codesydneywebsite#43]
#### Description
The Contributors component uses an array of contributors as its data. Every time we render the Contributors component, we create a new array and we do extra work when we don't have to.

The goal is to create this array once instead of every time we render. Good luck!

https://github.com/codesydney/codesydneywebsite/blob/3d32f03eb4edec6056446b80d23c20e00e140054/src/elements/Contributors/Contributors.jsx#L5-L16

#### Files
[Contributors.jsx
](https://github.com/codesydney/codesydneywebsite/blob/3d32f03eb4edec6056446b80d23c20e00e140054/src/elements/Contributors/Contributors.jsx)

**Comment by NimaSakha** [comment]
Hi, can I please work on this issue?

**Comment by davidtaing** [comment]
Thanks @NimaSakha, I've assigned you.

Let me know if you get stuck or otherwise need any other help.  🙂
