### ISSUE TITLE
Social icons in the footer overflow

### ISSUE THREAD

**Issue by rymnddev** [codesydney/codesydneywebsite#56]
![image](https://user-images.githubusercontent.com/49798957/179086371-959362e5-9760-4be8-831a-96696bdf4795.png)

Adding flex-wrap will probably suffice. I'd like to take care of it.

**Comment by rymnddev** [comment]
I get the following error when I try to push my changes. I've followed the playbook.

`git push origin "social-icons-in-the-footer-overflow"
remote: Permission to codesydney/codesydneywebsite.git denied to king-oldmate.
fatal: unable to access 'https://github.com/codesydney/codesydneywebsite.git/': The requested URL returned error: 403`

**Comment by davidtaing** [comment]
Hi @king-oldmate, you probably don't have write permissions to the repo.

Your local repo is pointing to the codesydney repository and not your fork.

You'll have to figure out how to change it so that you are pushing the changes to your fork.
