### ISSUE TITLE
Volunteers Management System

### ISSUE THREAD

**Issue by engramar** [codesydney/codesydneywebsite#6]
- Search/Filter of volunteer programmers 
- Ability to sign up as a volunteer and update profile 
- Links to preferred User portfolio pages (Default will be LinkedIn)
- Feel free to add

**Comment by Luukeeeee** [comment]
If signing up and updating functions are required, it seems we need an backend. Just wondering what we are going to use? Also, if sign up by users will be the case, how can we control who is able to sign up? So, backend user identical will be needed? Moreover, currently our website is a single page one. As the large volunteers volume now and in the future, it seems we need to put the volunteers page seperately?

**Comment by engramar** [comment]
Good morning @Luukeeeee , You are correct. There will be some backend work here and yes, it will be in a totally separate page. =) I put all roadmap items in there but it is up to the team as led by @QjStout on which one is to be prioritised. I will also leave it to the team on which tech stack to use. I am assuming MERN will be sort of a natural choice considering the site is now in React.

**Comment by QjStout** [comment]
@Luukeeeee I was thinking for the meantime we just use an Airtable but I'm open to other suggestions.

**Comment by QjStout** [comment]
I was thinking for the meantime we just use an Sortable buT I'm open to other suggestions

**Comment by engramar** [comment]
@QjStout Sounds like a good suggestion to user just a table as a start if we will prioritise this roadmap item. There is no urgency to introduce any self-service portal (i.e. signup/signin). We can just manually hardcode active members in a table as a start which I am sure is less than 20 anyway. =)

**Comment by QjStout** [comment]
And for the login part we gotta take a look at auth solutions for JAMstack.

**Comment by Luukeeeee** [comment]
> @Luukeeeee I was thinking for the meantime we just use an Airtable but I'm open to other suggestions.

Good suggestion @QjStout, I mean I got new thing to learn. :)

**Comment by QjStout** [comment]
It's super easy @Luukeeeee so no stress.
It's basically a ready to go backend to serve a database that you interact with through an easy to use table based UI. It's really great for anything placeholder or for weekend projects

**Comment by Luukeeeee** [comment]
> It's super easy @Luukeeeee so no stress.
> It's basically a ready to go backend to serve a database that you interact with through an easy to use table based UI. It's really great for anything placeholder or for weekend projects

It's cool mate, I am super excited to have new think to learn.😀

**Comment by Luukeeeee** [comment]
I have just got some spare time to work on the volunteers page. Currently, as I don't know which airtable account we suppose to use for the project, I have just been using some dummy data and done some initial work for the small screen layout. Including volunteers' cards, filter system, some css effection, as well as put header and footer section to the root for different pages. The branch has been push. Please, give me some suggestions when you guys get time, and I will work on the layout for large screen.

**Comment by engramar** [comment]
Morning @Luukeeeee. Thanks for that. Let me check your branch.

**Comment by Luukeeeee** [comment]
Thank you for your time. It's just the initial layout for the small screen.
A lot of aspects need to be improved or modified. Let me know what you
think.

Also, I'm thinking of using a totally different layout for the large
screen. Maybe something like the old website.

Moreover, do we need any description for the volunteers page? Also, I am
thinking of adding a skills section to each volunteer.

Let me know your thoughts.

Thanks

Engramar Bollas ***@***.***> 于 2022年2月24日周四 上午5:20写道：

**Comment by QjStout** [comment]
I actually quite like the current layout. I think we just need a navigation UI component

**Comment by QjStout** [comment]
@engramar what do you want to do about the Airtable account? Do you want to make one with an email that belongs to CodeSydney or something?
