### ISSUE TITLE
Projects Management System

### ISSUE THREAD

**Issue by engramar** [codesydney/codesydneywebsite#7]
- Search/Filter of Code.Sydney Projects
- Showcase project details and status 
- Feel free to add

**Comment by EllaFerreira** [comment]
Hello @engramar may I ask more details about the showcase project details you mentioned above?

**Comment by engramar** [comment]
Good morning @EllaFerreira. Thanks for asking. Actually I am planning to close this one for now. We can just focus on the marketplace one. It is pretty much the same as this. Cheers and thanks again for all your help.
