### ISSUE TITLE
Class based componants converstion to Function Header.jsx

### ISSUE THREAD

**Issue by infodsagar** [codesydney/codesydneywebsite#81]
With the latest version of React, it is recommended to avoid the use of class-based components.  As a part of upgrading the whole project, we can initiate the process with the following file Header.jsx

[src/component/header/Header.jsx](https://github.com/codesydney/codesydneywebsite/blob/main/src/component/header/Header.jsx)

**Comment by davidtaing** [comment]
Thanks for doing that @infodsagar. I've assigned this issue to you.
