### ISSUE TITLE
Class based componants converstion to Function Footer.jsx

### ISSUE THREAD

**Issue by infodsagar** [codesydney/codesydneywebsite#82]
With the latest version of React, it is recommended to avoid the use of class-based components. As a part of upgrading the whole project, we can initiate the process with the following file Footer.jsx

What we expected to do is define the Footer class as a function component.

https://github.com/codesydney/codesydneywebsite/blob/main/src/component/footer/Footer.jsx

**Comment by davidtaing** [comment]
Thanks for doing that @infodsagar. Since this version of the Header isn't being used, I'll change the issue to migrate the Footer component instead.

**Comment by infodsagar** [comment]
sure, I have updated the title of this issue.

**Comment by infodsagar** [comment]
I am closing the issue as it is resolved under this [commit ](a605806a88bbb5108333c2f731c468861f0e2482) Convert Footer to Function Component #84
