### ISSUE TITLE
Convert error404.jsx to Function Component

### ISSUE THREAD

**Issue by infodsagar** [codesydney/codesydneywebsite#88]
-To make code readable and clean convert class components to function and additional improvements.

-File [link](https://github.com/codesydney/codesydneywebsite/blob/351d1d10e310621cdf52bca83a3e63c1971c581b/src/elements/error404.jsx) & path src/elements/error404.jsx

**Comment by NimaSakha** [comment]
Hi Infodsagar, 
Can I please work on this issue?

**Comment by davidtaing** [comment]
Go for it! Assigned @NimaSakha.

Can you work in a new branch for this one though?

**Comment by davidtaing** [comment]
Oh, don't forget to update your local main branch as well @NimaSakha.

I believe it's either `git fetch` or `git pull` but double check.

**Comment by davidtaing** [comment]
Hey @NimaSakha, do you need help with this issue?

Not in a hurry for a reply. Don't rush with this one.

**Comment by NimaSakha** [comment]
Hi @davidtaing, ive been a bit busy learning react getting my self ready for the Jr dev aus project. But I will have this project dome some time this week
