### ISSUE TITLE
Convert Portfolio.jsx to Function Component

### ISSUE THREAD

**Issue by infodsagar** [codesydney/codesydneywebsite#96]
-To make code readable and clean convert class components to function and additional improvements.

-File [link](https://github.com/codesydney/codesydneywebsite/blob/f3b1092f53b3bdd954feba4f6ab09e43f983bbbe/src/component/HomeLayout/homeOne/Portfolio.jsx) & path src/component/HomeLayout/homeOne/Portfolio.jsx

**Comment by davidtaing** [comment]
@infodsagar, 
Would you like to work on this one?

I'd like you to extract the content into an array and from there figure out how to render the contents from the array.

@foadbotan, would you like to do the code review after Sagar has finished?

**Comment by foadbotan** [comment]
Sure, I’m happy to help.
